### ISSUE TITLE
TypeError: evaluate() got an unexpected keyword argument 'only_ema'

### ISSUE THREAD

**Issue by Feeeeeel** [Lans1ng/SFOD-RS#1]
File "test.py", line 262, in <module>
    main()
  File "test.py", line 254, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
TypeError: evaluate() got an unexpected keyword argument 'only_ema'

I followed the Install Environment instructions to install and train, but encountered the aforementioned error when running python test.py. It seems that there is no only_ema parameter in mmrotate. Does the author know how to fix this error?

**Comment by Lans1ng** [comment]
Thank you for your attention to our work. There was indeed a bug during testing. The most straightforward solution is to comment out the line with `only ema` during testing and use:`evaluation = dict(interval=test_interval, metric='mAP')`

**Comment by Feeeeeel** [comment]
I understand now, thanks for your work!
